glide.yaml
=> add glide dependency

mqtt.go
=> replace fmt with log

.gitignore
=> #1 Add git ignore file to filter some binary and IDE files

cache.go, controller.go, domain.go, filter.go, main.go, mqtt.go, proxyhandler.go, router.go, websocket.go
=> #11 Package statement and license should split with a blank line

router.go
=> #4 Use http.MethodGet to replace GET string const hard code

controller.go
=> #9 Change the comment style

const.go, controller.go, filter.go, main.go, mqtt.go, proxyhandler.go, router.go, websocket.go
=> #7 Use const to replace the hard code

cache.go, const.go, controller.go, domain.go, filter.go, main.go, mqtt.go, proxyhandler.go, router.go, websocket.go
=> #22 Format the whole project code

cache.go, domain.go, filter.go, main.go, mqtt.go, proxyhandler.go, websocket.go
=> #8 Remove dead code

README.md
=> #26 Add go report card

web/static/index.html, web/static/js/index.js, web/static/js/login.js, web/static/login.html
=> #41 Move javascript code snippets into specific javascript files

CONTRIBUTING.md
=> #43 Add CONTRIBUTING.md documentation

web/app/dao.go
=> #45 Define DAO interface for current domain objects

web/static/js/pages/export.js
=> fix exportshow

README.md
Signed-off-by: xiefayang <coderthank@163.com>
=> add how using git clone import project

web/static/js/index.js
Signed-off-by: gaofeng <gaofeng@jasgroup.cn>
=> fix IIFE expression can't run bug

web/app/domain.go, web/static/css/main.css, web/static/js/pages/export.js
1:  add background-color for sidebar
2: fix domain.go bug by add json format
3: export.js code cleanup
=> add new function and fix some bug

web/app/cache.go, web/app/controller.go, web/app/init.go, web/app/mongo_dao.go
=> #60 Use GatewayDao in GatewayController

cmd/edgex-ui-go/main.go
=> #71 Remove unused http server listen port 8080

cmd/edgex-ui-go/main.go
=> #70 Display the http listen port in main go file

configs/const.go, web/app/router.go
#77 Refactor configs/const to move most of them into web/app
=> #77 Refactor configs/const to move most of them into web/app

deployments/initmongo.js
#80 Provide an init script file for the mongodb
=> #80 Provide an init script file for the mongodb

web/app/domain/gateway.go, web/app/repository/gateway.go
=> #93 Can't return correct unix timestamp when get gateway data from db

deployments/README.md
=> #101 Add more information for mongodb install, init-seed and so on

web/app/mongo/mongo.go
=> #104 Refactor MongoDB connection initialize code

web/app/repository/mongo/gateway.go, web/app/repository/mongo/mongo.go, web/app/repository/mongo/user.go
=> #108 Remove all the hard code in repository package

web/app/controller/gateway.go, web/app/router.go
=> #112 Rename controller methods

README.md
=> #118 Add user login description in readme file

web/app/component/mqtt.go
#99 Fix mqtt address fit for edgex-go version logical
=> #99 Fix mqtt address fit for edgex-go version logical

web/static/js/pages/devices/device.js
Fix #114 Not remove addressable when delete a device
=> #114 Not remove addressable when delete a device

CONTRIBUTING.md, README.md, web/static/index.html, web/static/pages/devices/device.html, web/static/pages/devices/deviceProfile.html, web/static/pages/devices/deviceService.html, web/static/pages/export.html, web/static/pages/multimedia.html, web/static/pages/ruleengine.html
Signed-off-by: Brandon Forster <brandonforster@gmail.com>
=> #129: Spelling and grammar updates.

web/static/js/pages/ruleengine.js, web/static/pages/ruleengine.html
=> #132 RuleEngine menu bug when select Action data

web/static/css/devices/device.css, web/static/css/devices/deviceProfile.css, web/static/js/pages/devices/device.js, web/static/js/pages/devices/deviceProfile.js, web/static/js/pages/devices/deviceService.js, web/static/js/pages/export.js, web/static/js/pages/gateway.js
=> #126 ID field is displayed as a truncated value

web/app/common/filter.go
=> Code cleanup

web/static/js/pages/export.js
=> #138 Websocket connect failed when running with edgexfoundry in docker

web/static/js/pages/devices/device.js
=> #140 Didn't refresh data-list when execute a delete action

README.md, docker-file/Dockerfile
#52 Build edgex-ui-go docker image
=> #52 Build edgex-ui-go docker image
